# fly.toml app configuration file generated for yourl on 2023-06-19T10:09:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yourl"
primary_region = "lhr"

[http_service]
  internal_port = 3456
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
